[package]
name = "vidmod-plugins-cvbs"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
ndarray = "0.15.4"
vidmod-node = { version = "0.1.0", path = "../../vidmod-node" }
vidmod-plugin = { version = "0.1.0", path = "../../vidmod-plugin" }
